### ISSUE TITLE
Pet died and cant summon another

### ISSUE THREAD

**Issue by Mstori** [Safrodev/HoverPets#4] opened 2022-01-29 04:12 UTC
My panda pet got the wither effect from another mob and it died. Chat said panda pet withered away. Now I cant place another pet because it says I con only have one pet at a time but my "current" pet is dead.

**Comment by Safrodev** [comment] 2022-01-29 13:49
I believe I know where the issue is here. Sorry for the inconvenience.

**Comment by BryanBoru** [comment] 2022-02-17 02:29
Had a similar situation. Is there a command we can put in to "remove" the current assigned pet?

**Comment by Mstori** [comment] 2022-02-17 02:47
I restarted my server and it came back

**Comment by Safrodev** [comment] 2022-02-17 12:43
I will make sure to add a command in the next patch. There will also be some fixes so that your pet does not die to random sources.

**Comment by Safrodev** [comment] 2022-02-19 15:51
This should be fixed in version 0.2.0, including the addition of the removePet command.

**Closed as completed by Safrodev** 2022-02-19 15:51 UTC
Labels: bug

**Comment by BryanBoru** [comment] 2022-02-22 05:20
> 

slightly off topic, if they could lose the walking sounds/ stop shoving me around when catching up to me, that would be nice too. had some edge of platform close calls from that 🤣

**Comment by Safrodev** [comment] 2022-02-22 12:55
Lol, I can definitely remove the walking sounds. The following AI uses the same AI as wolves so I’ll have to see about the shoving part.

**Comment by BryanBoru** [comment] 2022-02-22 15:57
I appreciate your work, and of course make no demands, just requests. Thank you!
